version: "2.1"
services:
  tw-api:
    container_name: tw-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodata:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "\"db.runCommand('ping').ok\""] 
  tw-fetch:
    container_name: tw-fetch
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-FetchService
    volumes:
      - .:/usr/src/FetchService
    tty: true
    ports:
      - "9000:9000"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
